To do list review
SanaTameem/to-do-list-review pull request #1
Opened 2023-06-12 13:04 UTC by SanaTameem

This repo is for review.
- Javascript best practices.
- Clean and DRY code.

2023-06-12 15:23 UTC, Innocent259 requested changes
Hello @SanaTameem 

Good job so far!
You have made significant progress toward adopting best practices and writing clean code, but there are still a few areas that could benefit from further improvement.

![giphy](https://github.com/SanaTameem/to-do-list-review/assets/108480851/7bbd296e-8bcc-4348-8947-646f2f4cb0e4)

2023-06-12 16:07 UTC, Innocent259 requested changes
Hello @SanaTameem 

Good job so far!
You have made significant progress toward adopting best practices and writing clean code, but there are still a few areas that could benefit from further improvement.

![giphy](https://github.com/SanaTameem/to-do-list-review/assets/108480851/7bbd296e-8bcc-4348-8947-646f2f4cb0e4)

Correct use of GitHub Flow ✅
Use ES6 modules ✅
All linter checks are passing ✅
Descriptive PR title with a great summary ✅

You have done a great job creating the modules directory but it should be inside the src directory to maintain a clear and consistent codebase :smile:

2023-06-12 16:07 UTC, Innocent259 commented on modules/createItem.js
> +// eslint-disable-next-line
Disabling linter checks can lead to the accumulation of code quality issues and hinder the maintenance and readability of the codebase. Try to work on that.

2023-06-12 16:07 UTC, Innocent259 commented on modules/displayItem.js
> +// eslint-disable-next-line
Disabling linter checks can lead to the accumulation of code quality issues and hinder the maintenance and readability of the codebase. Try to work on that.

2023-06-12 16:07 UTC, Innocent259 commented on modules/displayItem.js
> +// eslint-disable-next-line
Disabling linter checks can lead to the accumulation of code quality issues and hinder the maintenance and readability of the codebase. Try to work on that.

2023-06-12 16:07 UTC, Innocent259 commented on src/index.html
> +    <script src="./newMainFile.js"></script>
When using Webpack, the script tag is typically not used directly in HTML files because Webpack bundles and manages JavaScript modules into a single file, which is then included in the HTML file using a script tag with the bundled file's path, allowing for better module management, dependency resolution, and optimization.

2023-06-14 05:17 UTC, Innocent259 approved these changes
Status: Approved 🎉 🎉 🎉

HI @SanaTameem 👋 👋 

![approve](https://github.com/SanaTameem/to-do-list-review/assets/108480851/b7a650fb-d809-4025-ac4b-af95b393c6e3)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

2023-06-14 07:04 UTC, SanaTameem commented on src/index.html
> +    <script src="./newMainFile.js"></script>
Thanks, I will do the changes you mentioned .

2023-06-14 07:05 UTC, SanaTameem commented on modules/displayItem.js
> +// eslint-disable-next-line
👍🏻

2023-06-14 07:05 UTC, SanaTameem commented on modules/displayItem.js
> +// eslint-disable-next-line
👍🏻

2023-06-14 07:05 UTC, SanaTameem commented on modules/createItem.js
> +// eslint-disable-next-line
👍🏻 Ok

2023-06-14 07:46 UTC, Innocent259 approved these changes
Status: Approved 🎉 🎉 🎉

Hi @SanaTameem 👋 👋

![approve](https://github.com/SanaTameem/to-do-list-review/assets/108480851/2130ed88-36e5-401c-98b8-45e1fb1d47aa)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

2023-06-14 09:22 UTC, merged